### ISSUE TITLE
Add getAllFiles method in Koldy\Request

### ISSUE THREAD

**Issue by zdrascic** [koldy/framework#1]
It would be helpful to have method for easier file manipulation from form-data requests in framework since we already have getAllGetParameters and getAllPostParameters

response can be unified Array of file objects that i can iterate and manipulate in project

**Comment by vkoudela** [comment]
Method `getAllFiles()` has been added [in this commit](https://github.com/koldy/framework/commit/92bd25ec728796fbaf7173872dacf822a8083491#diff-6b9eb1462366ea04805af50777a09800R844) so it can be used like this:

```php
$files = \Koldy\Request::getAllFiles();
```

It returns array of `UploadedFile` instances. Array follows the same structure as $_FILES and it fixes PHP's weird $_FILES structure when there's multiple files. Current code is available through Composer and `dev-master`.
